### ISSUE TITLE
test version 

### ISSUE THREAD

**Issue by domipelletier** [yreecht/Plateforme_PAMPA#1]
Hello, je ne mets que les "issues"! 
**1. Page d'entrée:**
Title: un 's' à resource ?
You can -> You may
Close all graphics ->Close all graphic windows
Restore data -> Restore imported data
Number of species codes in the imported file
Number of observations units in the imported file
start with standard treatments -> get started with graphics and statistical analyses

**2. Subsetting**
certains champs du referentiel espèces restent en FR:
Commerciales, Consommables, Emblématiques, facile...: ah ce sont celles du ref local je crois!
Après sélection: Infos de chargement reste en FR
ds cette fenetre: suppressed -> deleted

Selection sur facteur espece:
List of species reference factors -> List of species-related factors
Selection sur facteur station:
List of grouping factors -> List of station-related factors

**3. Graphics**
_combo de Graphics_
Per species (including per size class)
Several species or species-size class, aggregated by station -> Species groups (including per or over size classes) (je trouve que c'est aussi à changer en FR)
pourquoi on met "aggregated by station"? c'est aussi sur les légendes. Par ex. sur barplot, alors qu'en fait c'est la moyenne et l'écart-type. La légende devrait être:
"Mean (metric) per station for (selection) by (factors)" pour barplot
"Boxplot of (metric) per station for (selection) by (factors) " pour boxplot

_ds la boite de dialogue, il figure_:
a) Selection of variables for the boxplots (metrics aggregated /station)
-> Selection of metrics, factors and subsets for the boxplots
b) idem pour les barplots
c) Selection of the grouping factor(s) (same plot)->Selection of explanatory factors for plotting
(sur barplot et boxplot)
d) represented metrics-> Metric selection (sur barplot et boxplot)

_Occurrences_
Occurrence frequency (/observation unit factor) -> Frequencies
Occurrence frequency (/species, over observation units) -> Frequencies
Boites de dialogue correspondantes:
-Selection of variables for the occurrence frequencies ->Selection of explanatory factors and subsets for frequencies (2 fois: per species and for species groups)
-Calculated metrics: "occurrence frequency (/species group, over stations) -> Plotted metric : frequency per species group, and explanatory factor(s)(2 fois: per species and for species groups)
-from the station characteristics ->per obs. unit characteristic
-from the species reference table->species selection (one plot per selected species)

split the plots per factor (optional, 'species code' or 'identifiant' recommended):
-pourquoi on a le choix alors (on est dans le menu par espece), 
en fait si on choisit from the station..., on aura forcément un graphique faux, non?
car on ne pourra pas choisir l'espèce
-ne faut-il pas mettre:
Selection of factor or species (one plot per species) (NB: if species selection, select : 'species code',species'  or 'scient.name')

-Selection of the grouping/explaining factor(s)->Selection of explanatory factors for plotting

**4. Options graphiques** 
Graphics options ->Plot options (2 fois)
Display warning for low numbers
Statistics for the bar: moyenne s'affiche bien que qd on clique on voit mean et median

Text size (multiple of 1)

**Comment by domipelletier** [comment]
**Complément pour Data**
*Manual selection RAS
*Default directory and files: ouvre bien R ou Rstudio, produit quand meme une boite de dialogue avec message d'erreur : Loading information. There were errors while loading the data. Please check.....
*Check of the species reference table -> ne fait rien ?
*Sampling design: idem
*Data information per species: idem
*Data information per station: idem
est-ce censé faire qqe chose une fois les données importées ?
j'ai fermé et relancé la PF et cette fois, çà fait quelque chose:
*Ds information on referentiel especes, 
Filling rate of fields.....-> Documentation rate per field of the species reference file for observed species
(je suppose que c'est par rapport aux espèces présentes ds le fichier obs?)
Il met tjrs (current dataset with subsetting) meme si données restorées
*Sampling design: la fenetre ne contient rien
*dans Information per species, j'aurais mis au lieu de categories ->taxa/categories
je ne comprends pas la distinction entre "number of observed categories" et "number of taxonomic (biotic) observed categories"
This information accounts for....
Ce n'est pas important mais le save as a CSV produit un fichier de ce type:

X1.nrow,"V2","V3","V4" |   |   |  
-- | -- | -- | --
Incomplete,"Incomplete","Incomplete","Incomplete"
Incomplete,"Incomplete","Incomplete","Incomplete"
etc....

*Information per station: le fichier est comme celui de l'information sur les espèces (voir ex ci-dessus)

**Comment by yreecht** [comment]
All points addressed: [Test version #1_answers.pdf](https://github.com/yreecht/Plateforme_PAMPA/files/2826348/Test.version.1_answers.pdf)

See pre-release 3.0-beta2.
